name: Python syntax check

on:
  push:
  pull_request:

jobs:
  py_compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Compile Python files
        run: python -m py_compile memo.pyw memo_search.pyw
